spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gaehwa?currentSchema=public&characterEncoding=UTF-8
    driver-class-name: org.postgresql.Driver
    username: gaehwa
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

firebase:
  credentials:
    path: classpath:firebase/firebase-service-key.json

jwt:
  secret: ${JWT_SECRET}
  access-exp: 1800000  # 30분
  refresh-exp: 1209600000  # 14일

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []

server:
  port: 8080
  address: 0.0.0.0

